# Generated by Django 2.1.7 on 2019-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freedom_Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedom',
            name='countryid',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freedom',
            name='financial_freedom',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freedom',
            name='gdp_per_capita_ppp_USD',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freedom',
            name='investment_freedom',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freedom',
            name='region_rank',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freedom',
            name='world_rank',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
